# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9edb144ee59658d7c7b0a9b9606a1617856592e7932e2d1e6db806a16ddf772b944ad025910350efc40dddb0b5328f87ad29a10e4b4edb6fba1793eb87f403b

test:
  secret_key_base: 5d8bf48112ec396f24478b45e5b3fd7166d236de20af8d9fd2d5a29bd45b9ba0d5d3d87856a8cb003899f8f4584b79ffa0c98fdcf25194a0acd1d5d8844518db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
